### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by d-a-v** [x3mEr/ESP32-Dashcam#1]
Hello,

With a fresh esp32/arduino setup I get compilation errors.
The first one is
```
.../ESP32-Dashcam.ino:411:1: error: no return statement in function returning non-void [-Werror=return-type]
```

https://github.com/x3mEr/ESP32-Dashcam/blob/33bf785b42fc5c5939825c58f4643d8f193ab799/ESP32-Dashcam/ESP32-Dashcam.ino#L400-L411

I'd like to know if your motorcycle dashcam is still working. It is a great idea !
And whether you plan to fix your repository to the latest versions of the tools.

**Comment by x3mEr** [comment]
> I'd like to know if your motorcycle dashcam is still working. It is a great idea ! And whether you plan to fix your repository to the latest versions of the tools.

@d-a-v, Hello!) Thank you for your comment. The dashcam is still working) I flashed it a year ago and  never updated the firmware. I used the libraries included in the repository (just add them to the sketchbook location).
Arduino version 1.8.10
esp32 board version 1.0.4
Board "AI Thinker ESP32-CAM".

Right now, I don't have free time, but it should be repaired) Don't know yet when.
I'll add readme with versions mentioned above.

**Comment by x3mEr** [comment]
@d-a-v, Yesterday, I tested the code with newer versions of the libraries, board, Arduino IDE. Everything is OK, except for the esp32 board newer than 1.0.4. Googling showed that some projects (code) depend on the board version.
So this project is for esp32 ver. 1.0.4)

**Comment by x3mEr** [comment]
@d-a-v, further investigation showed:
1) code contains warnings. A lot of warnings are false)
2) esp32 board ver. 1.0.5 and above conflicts with WiFi lib.

To compile the project, in Arduino set IDE "File -> Preferences -> Compile warnings" to "default" ([here](https://github.com/jameszah/ESP32-CAM-Video-Recorder/issues/52))
