### ISSUE TITLE
Thank full for this project

### ISSUE THREAD

**Issue by satishsezu** [x3mEr/ESP32-Dashcam#2]
Thank full for this project I want to make and publish this project in my YouTube channel if you permit me, can you suggest app of this project to connect android  phone apology raising issue I cant able to find your contact inf so once aging thank you its relay good

**Comment by x3mEr** [comment]
@satishsezu, hello! Sorry for so late response.
Of course, you can make this project and publish video about it on your YouTube channel. Please, give me a URL after!)

"can you suggest app of this project to connect android phone" - I don't understand the question, actually. You can connect to the web server via any Internet browser on Android
