### ISSUE TITLE
Unsure how to setup button

### ISSUE THREAD

**Issue by zeroalphagit** [x3mEr/ESP32-Dashcam#3]
I'm getting this error:

> sketch\ESP32-Dashcam.ino.cpp.o:(.literal._Z11buttonsTickv+0xc): undefined reference to `GButton::tick()'
> sketch\ESP32-Dashcam.ino.cpp.o:(.literal._Z11buttonsTickv+0x10): undefined reference to `GButton::isSingle()'
> sketch\ESP32-Dashcam.ino.cpp.o:(.literal.startup._GLOBAL__sub_I_ESP_SSID+0x8): undefined reference to `GButton::GButton(unsigned char, unsigned char, unsigned char)'
> sketch\ESP32-Dashcam.ino.cpp.o: In function `buttonsTick()':
> C:\Users\dell\Documents\Arduino\ESP32-Dashcam-master\ESP32-Dashcam/ESP32-Dashcam.ino:285: undefined reference to `GButton::tick()'
> C:\Users\dell\Documents\Arduino\ESP32-Dashcam-master\ESP32-Dashcam/ESP32-Dashcam.ino:286: undefined reference to `GButton::isSingle()'
> sketch\ESP32-Dashcam.ino.cpp.o: In function `_GLOBAL__sub_I_ESP_SSID':
> C:\Users\dell\Documents\Arduino\ESP32-Dashcam-master\ESP32-Dashcam/ESP32-Dashcam.ino:887: undefined reference to `GButton::GButton(unsigned char, unsigned char, unsigned char)'
> collect2.exe: error: ld returned 1 exit status
> Multiple libraries were found for "WiFi.h"
>  Used: C:\Users\dell\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
>  Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\libraries\WiFi
> exit status 1
> Error compiling for board AI Thinker ESP32-CAM.

Is it because I'm not setting up the button? I'm not sure what to do

**Comment by x3mEr** [comment]
Hello, @zeroalphagit!)
Try to put the folder "GyverButton" from [ESP32-Dashcam/libraries](https://github.com/x3mEr/ESP32-Dashcam/tree/master/libraries) to the folder, where is all your libraries for Arduino IDE.
