### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by duedipicche** [x3mEr/ESP32-Dashcam#6]
This error appears during compilation in app_httpd.ccp

_exit status 1
fd_forward.h: No such file or directory_
or
_exit status 1
fr_forward.h: No such file or directory_

Arduino 1.8.42
Windows 10 Pro
ESP-Cam model _AIThinker
WIFI 1.2.7
DnsServer 2.0.0
EEPROM 2.0.0
FS 2.0.0
SD_MMC 2.0.0
WebServer 2.0.0
WiFiManager 2.0.12-beta

it would seem to have something to do with face detection and face recogniction.
thanks for your attention

**Comment by x3mEr** [comment]
It looks like new version of board causes this error.
Try to downgrade "esp32 by Espressif Systems" board to version 1.0.4.

**Comment by x3mEr** [comment]
The answer could be found here: https://github.com/espressif/arduino-esp32/issues/5878#issuecomment-966756467
Face recognition is removed from the Arduino IDE core from 2.0.1+

**Comment by duedipicche** [comment]
> It looks like new version of board causes this error. Try to downgrade "esp32 by Espressif Systems" board to version 1.0.4.

it's works Thanks

**Comment by lvca** [comment]
How can you downgrade it? Using platfom.io I tried to put espressif32@1.0.4 but this version doesn't exist (and it should be very old if existed).
